//d
//  login.ts
//
//  Generated by Poll Castillo on 15/02/2023.
//

import "./config.js"
import { getUserInfo, _userAgent, generateTokenVisit, NetliinkBase, basicAuth } from "./endpoints.js"
import { InterfaceElement, Request } from "./types.js"
import { contDown, getSearch } from "./tools.js"

const loginContainer: InterfaceElement = document.getElementById('login-container')
const app: InterfaceElement = document.getElementById('app')
const qrUser: string = window.APP_CONFIG?.consultaUser ?? 'qr'

const connectionHeader = {
    Accept: "application/json",
    "User-agent": _userAgent,
    Authorization: basicAuth,
    "Content-Type": "application/x-www-form-urlencoded",
    Cookie: "JSESSIONID=CDD208A868EAABD1F523BB6F3C8946AF",
}


const reqOP: Request = {
    url: `${NetliinkBase}oauth/token`,
    method: 'POST'
}

export class SignIn {
    public async checkSignIn(): Promise<void> {
        const accessToken = localStorage.getItem('access_token')
        const checkUser = async (): Promise<void> => {
            const currentUser = await getUserInfo()
            if (currentUser.error === 'invalid_token') {
                await this.accessToken()
                return
            }
            if (currentUser.username !== qrUser) {
                await this.accessToken()
                return
            }
            if(currentUser.username === qrUser){
                const valores = window.location.search;
                const urlParams = new URLSearchParams(valores);
                var dni = urlParams.get('visitas');
                if(dni == null || dni == '' || dni == undefined){
                    this.show404("Parámetro no encontrado")
                }else{
                    reg(dni)
                }                
            }
        }

        const reg = async (dni: any) => {
            let fecha = new Date();
            let mes: any = fecha.getMonth()+1
            let dia: any = fecha.getDate()
            let anio: any = fecha.getFullYear()
            if(dia<10)
                dia='0'+dia
            if(mes<10)
                mes='0'+mes
            let date: any = anio+"-"+mes+"-"+dia
            await getSearch("dni", `${dni}`, "Visit", `${date}`)
            .then((res) => {
                if(res == undefined){
                    this.show404("Visita no encontada, verificar estado de la empresa, cliente, usuario o visita")
                }else{
                    /*if (res.business?.state?.name !== 'Enabled') {
                        this.show404(`La empresa ${res.business?.name ?? ''} no se encuentra activa`)
                        return
                    }
                    if (res.customer?.state?.name !== 'Enabled') {
                        this.show404(`El cliente ${res.customer?.name ?? ''} no se encuentra activo`)
                        return
                    }
                    if (res.user?.state?.name !== 'Enabled') {
                        this.show404(`El usuario ${res.user?.username ?? ''} no se encuentra activo`)
                        return
                    }*/
                    if (res.customer?.permitVisitStatic === true) {
                        this.show404(`El cliente ${res.customer?.name ?? ''} solo permite códigos QR de visitas estáticos`)
                        return
                    }
                    if (res.calculatedDate && res.calculatedTime) {
                        let limitDate = new Date(`${res.calculatedDate}T${res.calculatedTime}`);
                        let now = new Date();
                        if (now > limitDate) {
                            this.show404("Visita expirada");
                            return;
                        }
                    }
                    this.showQr(res);
                }
            })
            .catch(error => {
                this.show404(error)
                console.log('error', error)
            })
        }

        if (accessToken) {
            checkUser()
        } else {
            this.accessToken()
        }

    }

    public showQr(data: any): void {
        const rawDni = data?.dni ?? ''
        //Ocultar lo de Fast para invitado rapido
        const checkDni = rawDni.includes('-FAST')
        let dni: any
        if(checkDni){
            //let fastLimit = rawDni.indexOf('-FAST')
            //let dniDetected = rawDni.slice(0, fastLimit)
            dni = ''
        }else{
            dni = rawDni
        }
        loginContainer.innerHTML = ''
        loginContainer.style.display = 'flex !important'
        loginContainer.innerHTML = `
        <div class="login_window">
        <div class="login_header">
          <img src="./public/src/assets/pictures/app_logo.png">
          <h1 class="login_title">QR VISITA</h1>
          <div class="input_detail">
            <label for="ingress-date"><i class="fa-solid fa-user"></i> ${data?.firstName ?? ''} ${data?.firstLastName ?? ''}</label><br>
            <label for="ingress-date"><i class="fa-solid fa-address-card"></i> ${dni}</label><br>
            <label for="ingress-date"><i class="fa-solid fa-calendar"></i> ${data?.creationDate ?? ''}</label><br>
            <label for="ingress-date"><i class="fa-solid fa-heartbeat"></i> ${data?.visitState?.name ?? ''}</label><br>
            <label for="ingress-date"><i class="fa-solid fa-share"></i> ${data?.user?.firstName ?? ''} ${data?.user?.lastName ?? ''}</label><br>
          </div>
        </div>
        <div class="login_content">
        <br>
            <div id="qrcode" style="display:flex;justify-content:center"></div>
            <br>
            <p class="timer-p">Expira en:</p>
            <div id="contdown" style="display:flex;justify-content:center"></div>
        </div>

        <div class="login_footer">
          <p>El código QR generado por minuto solo es válido para un único ingreso</p>
          <div class="foot_brief">
            <p>Desarrollado por</p>
            <img src="./public/src/assets/pictures/login_logo.png">
          </div>
        </div>
      </div>
        `
        this.signIn()
        this.intervalQr(data)
        window.addEventListener("beforeunload", function (e) {
            var confirmationMessage = "\o/";
          
            (e || window.event).returnValue = confirmationMessage; //Gecko + IE
            return confirmationMessage;                            //Webkit, Safari, Chrome
          });
    }

    public show404(message: string): void {
        loginContainer.innerHTML = ''
        loginContainer.style.display = 'flex !important'
        loginContainer.innerHTML = `
        <div class="login_window">
            <div class="login_header">
                <img src="./public/src/assets/pictures/app_logo.png">
                <h1 class="login_title">PORTAL QR VISITA</h1>
                <div class="input_detail">
                    <label for="ingress-date"><i class="fa-solid fa-exclamation-circle" style="color:red;"></i> Ha ocurrido un error: ${message}.</label><br>
                </div>
                </div>
                <div class="login_content" style="display:flex;justify-content:center">
                <br>
                    <img src="./public/src/assets/pictures/404.jpg" width="75%" height="75%">
                </div>

                <div class="login_footer">
                <div class="login_icons">
                    <i class="fa-regular fa-house"></i>
                    <i class="fa-regular fa-user"></i>
                    <i class="fa-regular fa-inbox"></i>
                    <i class="fa-regular fa-file"></i>
                    <i class="fa-regular fa-computer"></i>
                    <i class="fa-regular fa-mobile"></i>
                </div>
                <p>Accede a todas nuestras herramientas</p>

                <div class="foot_brief">
                    <p>Desarrollado por</p>
                    <img src="./public/src/assets/pictures/login_logo.png">
                </div>
            </div>
        </div>
        `
    }

    public showReload(): void {
        loginContainer.innerHTML = ''
        loginContainer.style.display = 'flex !important'
        loginContainer.innerHTML = `
        <div class="login_window">
            <div class="login_header">
                <img src="./public/src/assets/pictures/app_logo.png">
                <h1 class="login_title">PORTAL QR VISITA</h1>
                <div class="input_detail">
                    <label for="ingress-date"><i class="fa-solid fa-exclamation-circle" style="color:blue;"></i> Presione sobre la imagen para recargar.</label><br>
                </div>
                </div>
                <div class="login_content" style="display:flex;justify-content:center">
                <br>
                    <img id="reloadImg" src="./public/src/assets/pictures/recargar.png" width="75%" height="75%">
                </div>

                <div class="login_footer">
                <div class="login_icons">
                    <i class="fa-regular fa-house"></i>
                    <i class="fa-regular fa-user"></i>
                    <i class="fa-regular fa-inbox"></i>
                    <i class="fa-regular fa-file"></i>
                    <i class="fa-regular fa-computer"></i>
                    <i class="fa-regular fa-mobile"></i>
                </div>
                <p>Accede a todas nuestras herramientas</p>

                <div class="foot_brief">
                    <p>Desarrollado por</p>
                    <img src="./public/src/assets/pictures/login_logo.png">
                </div>
            </div>
        </div>
        `
        this.reloadPage()
    }

    public reloadPage(){
        const btnImage: InterfaceElement = document.querySelector('#reloadImg')
        btnImage.addEventListener('click', (e: any): void => {
            e.preventDefault()
            window.location.reload()
        })
    }

    private intervalQr(data: any){
        var counter = 10
        let i = 1;
        let change = async () => {
            // @ts-ignore
            document.getElementById("qrcode").innerHTML = ''
            //counter *= 10;
            await generateTokenVisit(data.id)
            .then(async (response: any) => {
                const newToken = response?.randomToken
                if (!newToken) {
                    this.show404("Fallo de servicio")
                    return
                }
                // @ts-ignore
                //new QRCode(document.getElementById("qrcode"), newToken)
                let qrCode = new QRCodeStyling({
                    //width: 300,
                    //height: 300,
                    type: "svg",
                    //typeNumber:0,
                    data: newToken,
                    image: "./public/src/assets/pictures/qr.png",
                    dotsOptions: {
                        color: "#000000", //"#002337FF",
                        //type: "rounded"
                    },
                    backgroundOptions: {
                        color: "white",
                    }
                    /*imageOptions: {
                        crossOrigin: "anonymous",
                        margin: 20
                    }*/
                });
                qrCode.append(document.getElementById("qrcode"))
                if(i <= 3) contDown()
                if(i < 3){
                    i++
                    const expiresAt = response?.expiresAt
                        ? new Date(response.expiresAt).getTime()
                        : Date.now() + 60000
                    counter = Math.max(expiresAt - Date.now(), 1000)
                    setTimeout(change, counter)
                }else{
                    setTimeout(() => this.showReload(), 60000)
                }
                
            })
            .catch(error => {
                console.log('error', error)
                this.show404(error?.message || "No se pudo generar el QR de visita")
            })
            
        }
        setTimeout(change, counter)

        
    }

    private signIn(): void {
        const form: InterfaceElement = document.querySelector('#login-form')
        //this.accessToken()
    }

    private async accessToken(): Promise<void> {
        localStorage.removeItem('access_token')
        const body = new URLSearchParams({
            grant_type: 'password',
            username: qrUser,
            password: qrUser
        })
        const reqOptions: {} = {
            method: reqOP.method,
            body: body.toString(),
            headers: connectionHeader
        }
        try {
            const response: Response = await fetch(reqOP.url, reqOptions)
            const result: any = await response.json()
            if (!response.ok || !result.access_token) {
                throw new Error(result.error_description || result.error || 'Bad credentials')
            }
            localStorage.setItem('access_token', result.access_token)
            window.location.reload()
        }
        catch (error) {
            console.error('Error al iniciar sesión con el usuario QR:', error)
            this.show404('No se pudo iniciar sesión con el usuario QR')
        }
    }

    public signOut(): void {
        this.accessToken()
    }

}
